t=()
t=(1,2,3)
print(t)
t=(1,'raju', 2)
print(t)
t=(1,(1,2,3), [1,'raju', 28,'abs']) 
print(t)
t=('satish')
type(t)
print(type(t))
t=('ram', )
type(t)
print(type(t))
t="satish", 
print(type(t))
t=('satish','murli','naveen')
print(t[1])
t=('ran', 'ekta', 'rraj')
print(t[-1])
t=('ram',('satis','krishna', 'kalu'))
print(t[1][2])
t=(1,2,3,4,5)
print(t[1:4])
print(t[:-2])
print(t[:])